### ISSUE TITLE
Is there any annotation for wally's location?

### ISSUE THREAD

**Issue by pai-dy** [vc1492a/Hey-Waldo#2]
Hi, I'm student in Korea.

Before question, I really appreciate of your effort of waldo labeling.

I was wondering that is there any csv file or json file which contains wally's location?

like cx,cy,w,h or x1,y1,x2,y2

**Comment by vc1492a** [comment]
Hi @PAIka2k! Great question, and happy to see you're interested in using the dataset. 

There is no file that describes the exact locations of Wally in the photographs typically used for bounding box solutions to object detection. However, I don't think it would be that much work and would appreciate a pull request if you have the time! Essentially, one can label the original images for locations of Wally, and then update the `image_processing.py` file in the root directory to keep track of locations and note which files contain and do not contain Wally.
